### ISSUE TITLE
User logs out on refreshing the page

### ISSUE THREAD

**Issue by varunbhaya03** [taniarascia/takenote#167] opened 2019-11-03 18:27 UTC
The users tends to log out if the page is refreshed

Steps:
Logged in success
Refreshed the page and was redirected to the main landing page asking me to sign-in again.

**Comment by varunbhaya03** [comment] 2019-11-03 18:32
@taniarascia Is the user auth saved into the redux store only? and we lose all state when refreshing the  page?

**Comment by taniarascia** [comment] 2019-11-04 01:10
What browser?

**Comment by taniarascia** [comment] 2019-11-04 16:31
I have no issues with Chrome, but FireFox and Safari seem to have issues with the Auth.

**Comment by varunbhaya03** [comment] 2019-11-04 19:20
I am able to reproduce the issue on my Chrome browser version : 78 
I am not asked to authorize everytime, just redirected to that home page again on refresh and have to click sign-in.

I think the react-router runs before the user auth is set to store that is why maybe. will try to debug this and try to find out. :)

**Comment by taniarascia** [comment] 2019-11-05 14:08
Okay, I tested Chrome, Opera, and Firefox, refreshed 10 times on each one and no issue. Safari still logs out immediately on refresh. Is it the same for you?

**Comment by taniarascia** [comment] 2019-11-05 14:13
After clearing all cookies, resetting all caches, and re-logging in, I can't replicate the issue on any browser. Can you confirm?

**Comment by ashinzekene** [comment] 2019-11-05 15:41
I can reproduce this issue, maybe try reducing your network speed

**Comment by taniarascia** [comment] 2019-11-05 19:25
Browser, OS? And have you deleted all history/cookies from the file and started over, because I had the issue until I did that.

**Comment by taniarascia** [comment] 2019-11-09 21:22
I could replicate the issue in iOS but I think I fixed it...could be wrong...

**Comment by Dantaro** [comment] 2019-11-10 15:44
@ashinzekene @varunbhaya03 can you please confirm if the issue was fixed for you?  I wasn't ever able to reproduce so I don't trust my own testing

**Comment by taniarascia** [comment] 2019-11-13 14:20
I’m going to close this as I was able to fix the issue on the instance I could replicate it. If anyone experiences it again, they can open a new issue.

**Closed by taniarascia** 2019-11-13 14:20 UTC
Labels: Type: Bug
